// 跨平台共享的 prop registry：所有平台（X、TikTok 等）都注册进同一个数组，
// 复用 definePropDefinitions 的编译期 propId 去重检查（见 dataTypes.ts）。
import { definePropDefinitions } from "./dataTypes";

export const PROPS = definePropDefinitions([
  {
    propId: "user_id", //用于content commerce等与USER表关联
    dataType: "TEXT",
    label: { en: "user id", zh: "user id" },
  },
  {
    propId: "source_user_id",
    dataType: "TEXT",
    label: { en: "source user id", zh: "源 user id" },
  },
  {
    propId: "name",
    dataType: "TEXT",
    entity: ["user"],
    label: { en: "Name", zh: "名称" },
  },
  {
    propId: "username",
    dataType: "TEXT",
    entity: ["user"],
    label: { en: "Username", zh: "用户名" },
  },
  {
    propId: "is_follow",
    isInsight: true,
    dataType: "ENUM_INT",
    entity: ["user"],
    label: { en: "Is following", zh: "是否关注" },
    enums: [
      { value: 0, label: { en: "Not following", zh: "未关注" } },
      { value: 1, label: { en: "Following", zh: "关注中" } },
    ],
  },
  {
    propId: "is_followed",
    isInsight: true,
    dataType: "ENUM_INT",
    entity: ["user"],
    label: { en: "Is followed", zh: "是否被关注" },
    enums: [
      { value: 0, label: { en: "Not followed", zh: "未被关注" } },
      { value: 1, label: { en: "Followed", zh: "被关注中" } },
    ],
  },
  {
    propId: "verified_type",
    isInsight: true,
    dataType: "ENUM_TEXT",
    label: { en: "Verification Type", zh: "认证类型" },
    enums: [
      { value: "blue", label: { en: "Blue Verified", zh: "蓝V" } },
      { value: "none", label: { en: "None", zh: "无" } },
    ],
  },
  {
    propId: "description",
    dataType: "TEXT",
    entity: ["user"],
    label: { en: "Description", zh: "描述" },
  },
  {
    propId: "profile_image_url",
    dataType: "TEXT",
    fieldType: "IMAGE",
    entity: ["user"],
    label: { en: "Avatar", zh: "头像" },
  },
  {
    propId: "followers_count",
    isInsight: true,
    dataType: "INT",
    entity: ["user"],
    label: { en: "Followers", zh: "粉丝数" },
  },
  {
    propId: "following_count",
    isInsight: true,
    dataType: "INT",
    entity: ["user"],
    label: { en: "Following", zh: "关注数" },
  },
  {
    propId: "post_count",
    isInsight: true,
    dataType: "INT",
    entity: ["user"],
    label: { en: "Posts", zh: "发帖数" },
  },
  {
    propId: "listed_count",
    isInsight: true,
    dataType: "INT",
    entity: ["user"],
    label: { en: "Lists", zh: "收藏数" },
  },
  {
    propId: "like_count",
    isInsight: true,
    dataType: "INT",
    entity: ["user", "content"],
    label: { en: "Likes", zh: "点赞数" },
  },
  {
    propId: "media_count",
    isInsight: true,
    dataType: "INT",
    entity: ["user"],
    label: { en: "Medias", zh: "多媒体数" },
  },
  {
    propId: "message_text",
    isInsight: true,
    dataType: "TEXT",
    label: { en: "Text", zh: "文本" },
  },
  {
    propId: "message_image",
    dataType: "IMAGE",
    label: { en: "Image", zh: "图片" },
  },
  {
    propId: "message_video",
    dataType: "VIDEO",
    label: { en: "Video", zh: "视频" },
  },
  {
    propId: "source_created_at",
    isInsight: true,
    dataType: "DATETIME",
    entity: ["content"],
    label: { en: "Posted at", zh: "发布时间" },
  },
  {
    propId: "source_content_id",
    dataType: "TEXT",
    label: { en: "Source Content ID", zh: "源 Content ID" },
  },
  {
    propId: "content_type",
    isInsight: true,
    dataType: "ENUM_TEXT",
    entity: ["content"],
    label: { en: "Content Type", zh: "内容类型" },
    enums: [
      { value: "TWEET", label: { en: "Tweet", zh: "推文" } },
      { value: "ARTICLE", label: { en: "Article", zh: "文章" } },
      { value: "VIDEO", label: { en: "Video", zh: "视频" } },
    ],
  },
  {
    propId: "title",
    dataType: "TEXT",
    entity: ["content"],
    label: { en: "Title", zh: "标题" },
  },
  {
    propId: "content_text",
    dataType: "TEXT",
    entity: ["content"],
    label: { en: "Content Text", zh: "内容文本" },
  },
  {
    propId: "cover_image_url",
    dataType: "TEXT",
    fieldType: "IMAGE",
    entity: ["content"],
    label: { en: "Cover", zh: "封面" },
  },
  {
    propId: "duration",
    isInsight: true,
    dataType: "INT",
    entity: ["content"],
    label: { en: "Duration", zh: "时长" },
  },
  {
    propId: "height",
    isInsight: true,
    dataType: "INT",
    entity: ["content"],
    label: { en: "Height", zh: "高度" },
  },
  {
    propId: "width",
    isInsight: true,
    dataType: "INT",
    entity: ["content"],
    label: { en: "Width", zh: "宽度" },
  },
  {
    propId: "bookmark_count",
    isInsight: true,
    dataType: "INT",
    entity: ["content"],
    label: { en: "Bookmarks", zh: "收藏数" },
  },
  {
    propId: "view_count",
    isInsight: true,
    dataType: "INT",
    entity: ["content"],
    label: { en: "Views", zh: "浏览数" },
  },
  {
    propId: "quote_count",
    isInsight: true,
    dataType: "INT",
    entity: ["content"],
    label: { en: "Quotes", zh: "Quotes" },
  },
  {
    propId: "reply_count",
    isInsight: true,
    dataType: "INT",
    entity: ["content"],
    label: { en: "Replies", zh: "回复数" },
  },
  {
    propId: "repost_count",
    isInsight: true,
    dataType: "INT",
    entity: ["content"],
    label: { en: "Reposts", zh: "转发数" },
  },
  {
    propId: "share_count",
    isInsight: true,
    dataType: "INT",
    entity: ["content"],
    label: { en: "Shares", zh: "分享数" },
  },
]);
