name = "flow"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "none"
run_worker_first = true

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
invocation_logs = true

[env.dev]
name = "flow-dev"
routes = [{ pattern = "flow-dev.uni-scrm.com", custom_domain = true }]

[env.dev.vars]
WEB_URL = "https://web-dev.uni-scrm.com"
LINK_URL = "https://link-dev.uni-scrm.com"
CF_ACCOUNT_ID = "b34f3ff4aec4c36584672d5bf1320757"

[[env.dev.d1_databases]]
binding = "WEB_DB"
database_name = "uniscrm-web-dev"
database_id = "899d288e-198c-49d9-824b-bd8d5c0a3cb8"

[[env.dev.d1_databases]]
binding = "FLOW_DB"
database_name = "uniscrm-flow-dev"
database_id = "68362488-c13f-4b15-a666-7282d1b0e430"
migrations_dir = "migrations"

[[env.dev.d1_databases]]
binding = "ADMIN_DB"
database_name = "uniscrm-admin-dev"
database_id = "e82f67f3-3571-473f-abf4-fa0ad5a309a2"

[[env.dev.queues.consumers]]
queue = "uniscrm-event-dev"
max_batch_size = 10
max_batch_timeout = 5

[[env.dev.queues.consumers]]
queue = "uniscrm-flow-log-dev"
max_batch_size = 50
max_batch_timeout = 10

[[env.dev.queues.producers]]
binding = "FLOW_LOG_QUEUE"
queue = "uniscrm-flow-log-dev"

[[env.dev.pipelines]]
binding = "PIPELINE_FLOW_LOG"
stream = "e39cbcf14b494c51b3d9ad5f01076e7d"

[env.dev.ai]
binding = "AI"

[env.dev.triggers]
crons = ["* * * * *"]

[env.production]
name = "flow"
routes = [{ pattern = "flow.uni-scrm.com", custom_domain = true }]

[env.production.vars]
WEB_URL = "https://web.uni-scrm.com"
LINK_URL = "https://link.uni-scrm.com"

[[env.production.d1_databases]]
binding = "DB"
database_name = "uniscrm-web"
database_id = "98ea05ba-91de-423d-9126-aa3cd9b42382"

[[env.production.d1_databases]]
binding = "FLOW_DB"
database_name = "uniscrm-flow"
database_id = "a6525634-a740-42ce-964f-0da6324afdb1"
migrations_dir = "migrations"

[[env.production.d1_databases]]
binding = "ADMIN_DB"
database_name = "uniscrm-admin"
database_id = "ecf7a3be-2457-4e40-a537-bab4cc0ec281"

[[env.production.queues.consumers]]
queue = "uniscrm-event"
max_batch_size = 10
max_batch_timeout = 5

[[env.production.queues.consumers]]
queue = "uniscrm-flow-log"
max_batch_size = 50
max_batch_timeout = 10

[[env.production.queues.producers]]
binding = "FLOW_LOG_QUEUE"
queue = "uniscrm-flow-log"

[[env.production.pipelines]]
binding = "PIPELINE_FLOW_LOG"
stream = "64ad6d8c53ed4d179de5036524f755d5"

[env.production.ai]
binding = "AI"

[env.production.triggers]
crons = ["* * * * *"]
