FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir yt-dlp flask boto3

WORKDIR /app
COPY main.py .

EXPOSE 8080
CMD ["python", "main.py"]
