name = "link"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "none"
run_worker_first = true

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
invocation_logs = true

[env.dev]
name = "link-dev"
routes = [{ pattern = "link-dev.uni-scrm.com", custom_domain = true }]

[env.dev.vars]
LINK_URL = "https://link-dev.uni-scrm.com"
TREND_RETENTION_DAYS = "30"
WEB_URL = "https://web-dev.uni-scrm.com"
CF_ACCOUNT_ID = "b34f3ff4aec4c36584672d5bf1320757"
INTERNAL_SECRET = "dev-internal-secret"
X_CLIENT_ID = "cS1kY2RlNnc1VldHSWw0LVJQSFM6MTpjaQ"
TIKTOK_CLIENT_KEY = "sbaw7873x5p4wuwsiw"

[[env.dev.d1_databases]]
binding = "LINK_DB"
database_name = "uniscrm-link-dev"
database_id = "464f02da-5a53-438d-8f7b-f92519cf8bd9"
migrations_dir = "migrations"

[[env.dev.d1_databases]]
binding = "WEB_DB"
database_name = "uniscrm-web-dev"
database_id = "899d288e-198c-49d9-824b-bd8d5c0a3cb8"

[[env.dev.kv_namespaces]]
binding = "KV"
id = "9f65b37e6ac94f81948a0018f816f89f"

[[env.dev.vectorize]]
binding = "VECTORIZE"
index_name = "uniscrm-embeddings-dev"

[env.dev.ai]
binding = "AI"

[[env.dev.queues.producers]]
binding = "MAIGRET_QUEUE"
queue = "uniscrm-maigret-dev"

[[env.dev.queues.producers]]
binding = "FLOW_QUEUE"
queue = "uniscrm-event-dev"

[[env.dev.pipelines]]
binding = "PIPELINE_EVENT"
stream = "ef8f86e0735341bcb538af6ef0b40950"

[[env.dev.pipelines]]
binding = "PIPELINE_USER"
stream = "9f1592f3a469465bb21b55fd73e62d66"

[env.dev.triggers]
crons = ["0 * * * *"]

[env.production]
name = "link"
routes = [{ pattern = "link.uni-scrm.com", custom_domain = true }]

[env.production.vars]
LINK_URL = "https://link.uni-scrm.com"
TREND_RETENTION_DAYS = "30"
WEB_URL = "https://web.uni-scrm.com"
X_CLIENT_ID = "cXVhYUNyWVJWSlFtdFdjekt3V1U6MTpjaQ"

[[env.production.d1_databases]]
binding = "LINK_DB"
database_name = "uniscrm-link"
database_id = "279a86a5-985c-4a22-8d50-ebc64c8ed63b"
migrations_dir = "migrations"

[[env.production.d1_databases]]
binding = "WEB_DB"
database_name = "uniscrm-web"
database_id = "98ea05ba-91de-423d-9126-aa3cd9b42382"

[[env.production.kv_namespaces]]
binding = "KV"
id = "9f65b37e6ac94f81948a0018f816f89f"

[[env.production.vectorize]]
binding = "VECTORIZE"
index_name = "uniscrm-embeddings"

[env.production.ai]
binding = "AI"

[[env.production.queues.producers]]
binding = "MAIGRET_QUEUE"
queue = "uniscrm-maigret"

[[env.production.queues.producers]]
binding = "FLOW_QUEUE"
queue = "uniscrm-event"

[[env.production.pipelines]]
binding = "PIPELINE_EVENT"
stream = "a0ee570cbd4842b0b11e30af75abb779"

[[env.production.pipelines]]
binding = "PIPELINE_USER"
stream = "c62a940e5b6b45b4aa865ea808caa3b0"

[env.production.triggers]
crons = ["0 * * * *"]
