name = "admin"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
head_sampling_rate = 1

[env.dev]
name = "admin-dev"
routes = [{ pattern = "admin-dev.uni-scrm.com", custom_domain = true }]

[env.dev.triggers]
crons = ["0 */6 * * *"]

[env.dev.vars]
INTERNAL_SECRET = "dev-internal-secret"
CF_ACCOUNT_ID = "b34f3ff4aec4c36584672d5bf1320757"
STRIPE_PRICE_PRO = "price_1TiW9PLhYonpsSAWQbGlYm9D"
STRIPE_PRICE_PREMIUM = "price_1TiW9sLhYonpsSAWeyyfaQUU"

[[env.dev.d1_databases]]
binding = "ADMIN_DB"
database_name = "uniscrm-admin-db-dev"
database_id = "41e0db26-7267-4412-85b2-37c33be6a9a2"

[[env.dev.d1_databases]]
binding = "WEB_DB"
database_name = "uniscrm-db-dev"
database_id = "95ad8842-5b0d-4ff4-854d-9c42f4b0685f"

[env.production]
name = "admin"
routes = [{ pattern = "admin.uni-scrm.com", custom_domain = true }]

[[env.production.d1_databases]]
binding = "DB"
database_name = "uniscrm-db"
database_id = "ccd56e94-b85c-4144-ac18-a6946897a5b3"
