name = "admin"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
head_sampling_rate = 1

[env.dev]
name = "admin-dev"
routes = [{ pattern = "admin-dev.uni-scrm.com", custom_domain = true }]

[env.dev.triggers]
crons = ["0 */6 * * *"]

[env.dev.vars]
CF_ACCOUNT_ID = "b34f3ff4aec4c36584672d5bf1320757"
ENVIRONMENT = "dev"
STRIPE_PRICE_BASIC = "price_1TiW9PLhYonpsSAWQbGlYm9D"
STRIPE_PRICE_PRO = "price_1TiW9sLhYonpsSAWeyyfaQUU"
INTERNAL_SECRET = "dev-internal-secret"

[[env.dev.d1_databases]]
binding = "ADMIN_DB"
database_name = "uniscrm-admin-dev"
database_id = "e82f67f3-3571-473f-abf4-fa0ad5a309a2"

[[env.dev.d1_databases]]
binding = "WEB_DB"
database_name = "uniscrm-web-dev"
database_id = "899d288e-198c-49d9-824b-bd8d5c0a3cb8"

[env.production]
name = "admin"
routes = [{ pattern = "admin.uni-scrm.com", custom_domain = true }]

[env.production.vars]
INTERNAL_SECRET = "prod-internal-secret-change-me"
ENVIRONMENT = "production"

[[env.production.d1_databases]]
binding = "ADMIN_DB"
database_name = "uniscrm-admin"
database_id = "ecf7a3be-2457-4e40-a537-bab4cc0ec281"
migrations_dir = "migrations"

[[env.production.d1_databases]]
binding = "WEB_DB"
database_name = "uniscrm-web"
database_id = "98ea05ba-91de-423d-9126-aa3cd9b42382"
