name = "uniscrm-web"
main = "worker/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "none"
run_worker_first = true

[observability]
enabled = true
head_sampling_rate = 1

[env.dev]
name = "uniscrm-web-dev"
routes = [{ pattern = "web-dev.uni-scrm.com", custom_domain = true }]

[env.dev.vars]
GOOGLE_CLIENT_ID = "1038882920781-unbsoa2prpnvqufeicaqqe1mlgso5ac9.apps.googleusercontent.com"
X_CLIENT_ID = "cS1kY2RlNnc1VldHSWw0LVJQSFM6MTpjaQ"
APP_URL = "https://web-dev.uni-scrm.com"
LINK_SOCIAL_URL = "https://link-social-dev.uni-scrm.com"
INTERNAL_SECRET = "dev-internal-secret"
ADMIN_URL = "https://admin-dev.uni-scrm.com"

[[env.dev.kv_namespaces]]
binding = "KV"
id = "ac8b64b59ac540e0ab482f25bb78d41e"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "trend-skill-db-dev"
database_id = "b322777d-6617-4dbf-a4d2-f734166b7737"

[[env.dev.vectorize]]
binding = "VECTORIZE"
index_name = "trend-embeddings-dev"

[env.dev.ai]
binding = "AI"

[env.production]
name = "uniscrm-web"
routes = [{ pattern = "web.uni-scrm.com", custom_domain = true }]

[env.production.vars]
GOOGLE_CLIENT_ID = "1038882920781-qado86f0g0hcf7t3l74b8acgu1a8teg4.apps.googleusercontent.com"
X_CLIENT_ID = "cXVhYUNyWVJWSlFtdFdjekt3V1U6MTpjaQ"
APP_URL = "https://web.uni-scrm.com"
LINK_SOCIAL_URL = "https://link-social.uni-scrm.com"
ADMIN_URL = "https://admin.uni-scrm.com"

[[env.production.kv_namespaces]]
binding = "KV"
id = "88bc8c114dfb4ec3a77589c64f991a2e"

[[env.production.d1_databases]]
binding = "DB"
database_name = "trend-skill-db"
database_id = "ccd56e94-b85c-4144-ac18-a6946897a5b3"

[[env.production.vectorize]]
binding = "VECTORIZE"
index_name = "trend-embeddings"

[env.production.ai]
binding = "AI"
