name = "web"
main = "worker/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "none"
run_worker_first = true

[observability]
enabled = true
head_sampling_rate = 1

[env.dev]
name = "web-dev"
routes = [{ pattern = "web-dev.uni-scrm.com", custom_domain = true }]

[env.dev.triggers]
crons = ["*/5 * * * *"]

[env.dev.vars]
GOOGLE_CLIENT_ID = "1038882920781-unbsoa2prpnvqufeicaqqe1mlgso5ac9.apps.googleusercontent.com"
X_CLIENT_ID = "cS1kY2RlNnc1VldHSWw0LVJQSFM6MTpjaQ"
WEB_URL = "https://web-dev.uni-scrm.com"
LINK_URL = "https://link-dev.uni-scrm.com"
ADMIN_URL = "https://admin-dev.uni-scrm.com"
INTERNAL_SECRET = "dev-internal-secret"

[[env.dev.kv_namespaces]]
binding = "KV"
id = "9f65b37e6ac94f81948a0018f816f89f"

[[env.dev.d1_databases]]
binding = "WEB_DB"
database_name = "uniscrm-web-dev"
database_id = "899d288e-198c-49d9-824b-bd8d5c0a3cb8"

[[env.dev.vectorize]]
binding = "VECTORIZE"
index_name = "uniscrm-embeddings-dev"

[env.dev.ai]
binding = "AI"

[[env.dev.send_email]]
name = "EMAIL_WEB"
allowed_sender_addresses = ["noreply@uni-scrm.com"]

[env.production]
name = "web"
routes = [{ pattern = "web.uni-scrm.com", custom_domain = true }]

[env.production.triggers]
crons = ["*/5 * * * *"]

[env.production.vars]
GOOGLE_CLIENT_ID = "1038882920781-qado86f0g0hcf7t3l74b8acgu1a8teg4.apps.googleusercontent.com"
X_CLIENT_ID = "cXVhYUNyWVJWSlFtdFdjekt3V1U6MTpjaQ"
WEB_URL = "https://web.uni-scrm.com"
LINK_URL = "https://link.uni-scrm.com"
ADMIN_URL = "https://admin.uni-scrm.com"
INTERNAL_SECRET = "prod-internal-secret-change-me"

[[env.production.kv_namespaces]]
binding = "KV"
id = "9f65b37e6ac94f81948a0018f816f89f"

[[env.production.d1_databases]]
binding = "WEB_DB"
database_name = "uniscrm-web"
database_id = "98ea05ba-91de-423d-9126-aa3cd9b42382"

[[env.production.vectorize]]
binding = "VECTORIZE"
index_name = "uniscrm-embeddings"

[env.production.ai]
binding = "AI"

[[env.production.send_email]]
name = "EMAIL_WEB"
allowed_sender_addresses = ["noreply@uni-scrm.com"]
